# Generated by Django 2.2.5 on 2022-01-27 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=255, verbose_name='이름')),
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='아이디')),
                ('password', models.CharField(max_length=255, verbose_name='비밀번호')),
                ('email', models.EmailField(default='', max_length=128, unique=True, verbose_name='이메일')),
                ('usergender', models.CharField(choices=[('M', '남성(Man)'), ('W', '여성(Woman)')], max_length=1, verbose_name='성별')),
                ('location', models.CharField(choices=[('O', '승낙(O)'), ('X', '거절(X)')], max_length=1, verbose_name='위치')),
                ('country', models.CharField(max_length=100, verbose_name='지역')),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
