<<<<<<< HEAD
# Generated by Django 2.2.5 on 2022-01-27 14:02
=======
# Generated by Django 2.2.5 on 2022-01-26 08:26
>>>>>>> origin/ccc

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=300, verbose_name='이름')),
                ('id', models.CharField(max_length=300, primary_key=True, serialize=False, verbose_name='아이디')),
                ('password', models.CharField(max_length=300, verbose_name='비밀번호')),
                ('email', models.EmailField(default='', max_length=128, unique=True, verbose_name='이메일')),
                ('location', models.CharField(choices=[('O', '승낙(O)'), ('X', '거절(X)')], max_length=1, verbose_name='위치')),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
