# Generated by Django 2.2.5 on 2022-01-27 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miniproject', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
