# Generated by Django 4.0.1 on 2022-01-26 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommonPlace',
            fields=[
                ('place_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('place_name', models.TextField(null=True)),
                ('phone', models.TextField(null=True)),
                ('lat', models.TextField(null=True)),
                ('lng', models.TextField(null=True)),
                ('road_address', models.TextField(null=True)),
                ('info', models.BigIntegerField(null=True)),
                ('rate', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'place_common',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='museumDetail',
            fields=[
                ('place_id', models.OneToOneField(db_column='place_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main.commonplace')),
                ('website', models.TextField(null=True)),
                ('week_begin', models.TextField(null=True)),
                ('week_end', models.TextField(null=True)),
                ('holiday_begin', models.TextField(null=True)),
                ('holiday_end', models.TextField(null=True)),
                ('close_info', models.TextField(null=True)),
            ],
            options={
                'db_table': 'museum_detail',
                'managed': False,
            },
        ),
    ]
