# Generated by Django 4.0.1 on 2022-01-27 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.IntegerField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=100, null=True)),
                ('date', models.DateField()),
                ('rate', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'comment',
                'managed': False,
            },
        ),
    ]
